language: node_js
node_js:
  - "13.7.0"
services:
  - docker
before_install:
  - docker build -t rozdolsky33/new-wave4-front-end -f Dockerfile.dev .

script:
  - docker run -e CI=true rozdolsky33/new-wave4-front-end npm test
